// Permission constants and utilities

// Permission naming convention: RESOURCE_ACTION
// Examples: VIEW_USERS, CREATE_USER, DELETE_USER

export const PERMISSIONS = {
  // User Management
  VIEW_USERS: 'VIEW_USERS',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  SUSPEND_USER: 'SUSPEND_USER',
  RESET_PASSWORD: 'RESET_PASSWORD',
  
  // Role Management
  VIEW_ROLES: 'VIEW_ROLES',
  CREATE_ROLE: 'CREATE_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  ASSIGN_ROLE_TO_USER: 'ASSIGN_ROLE_TO_USER',
  REMOVE_ROLE_FROM_USER: 'REMOVE_ROLE_FROM_USER',
  
  // Permission Management
  VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
  CAN_ADD_PERMISSION_TO_ROLE: 'CAN_ADD_PERMISSION_TO_ROLE',
  CAN_REMOVE_PERMISSION_FROM_ROLE: 'CAN_REMOVE_PERMISSION_FROM_ROLE',
  
  // System Configuration
  VIEW_SYSTEM_SETTINGS: 'VIEW_SYSTEM_SETTINGS',
  MANAGE_SYSTEM_SETTINGS: 'MANAGE_SYSTEM_SETTINGS',
  VIEW_FEATURE_FLAGS: 'VIEW_FEATURE_FLAGS',
  MANAGE_FEATURE_FLAGS: 'MANAGE_FEATURE_FLAGS',
  
  // Data Management
  VIEW_TRANSACTIONS: 'VIEW_TRANSACTIONS',
  MANAGE_TRANSACTIONS: 'MANAGE_TRANSACTIONS',
  EXPORT_DATA: 'EXPORT_DATA',
  IMPORT_DATA: 'IMPORT_DATA',
  
  // Notifications
  VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS',
  SEND_NOTIFICATIONS: 'SEND_NOTIFICATIONS',
  MANAGE_TEMPLATES: 'MANAGE_TEMPLATES',
  DELETE_NOTIFICATIONS: 'DELETE_NOTIFICATIONS',
  
  // Audit Logs
  VIEW_LOGS: 'VIEW_LOGS',
  EXPORT_LOGS: 'EXPORT_LOGS',
  CREATE_LOGS: 'CREATE_LOGS',
  
  // API Keys
  VIEW_API_KEYS: 'VIEW_API_KEYS',
  CREATE_API_KEY: 'CREATE_API_KEY',
  DELETE_API_KEY: 'DELETE_API_KEY',
  
  // Analytics
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  EXPORT_ANALYTICS: 'EXPORT_ANALYTICS',
  
  // Dashboard
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
} as const

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS]

// Permission categories for UI organization
export const PERMISSION_CATEGORIES = {
  USER_MANAGEMENT: 'User Management',
  ROLE_MANAGEMENT: 'Role Management',
  SYSTEM_CONFIG: 'System Configuration',
  DATA_MANAGEMENT: 'Data Management',
  NOTIFICATIONS: 'Notifications',
  AUDIT_LOGS: 'Audit Logs',
  API_KEYS: 'API Keys',
  ANALYTICS: 'Analytics',
  DASHBOARD: 'Dashboard',
} as const

// Permission to category mapping
export const PERMISSION_CATEGORY_MAP: Record<Permission, string> = {
  [PERMISSIONS.VIEW_USERS]: PERMISSION_CATEGORIES.USER_MANAGEMENT,
  [PERMISSIONS.CREATE_USER]: PERMISSION_CATEGORIES.USER_MANAGEMENT,
  [PERMISSIONS.UPDATE_USER]: PERMISSION_CATEGORIES.USER_MANAGEMENT,
  [PERMISSIONS.DELETE_USER]: PERMISSION_CATEGORIES.USER_MANAGEMENT,
  [PERMISSIONS.SUSPEND_USER]: PERMISSION_CATEGORIES.USER_MANAGEMENT,
  [PERMISSIONS.RESET_PASSWORD]: PERMISSION_CATEGORIES.USER_MANAGEMENT,
  
  [PERMISSIONS.VIEW_ROLES]: PERMISSION_CATEGORIES.ROLE_MANAGEMENT,
  [PERMISSIONS.CREATE_ROLE]: PERMISSION_CATEGORIES.ROLE_MANAGEMENT,
  [PERMISSIONS.UPDATE_ROLE]: PERMISSION_CATEGORIES.ROLE_MANAGEMENT,
  [PERMISSIONS.DELETE_ROLE]: PERMISSION_CATEGORIES.ROLE_MANAGEMENT,
  [PERMISSIONS.ASSIGN_ROLE_TO_USER]: PERMISSION_CATEGORIES.ROLE_MANAGEMENT,
  [PERMISSIONS.REMOVE_ROLE_FROM_USER]: PERMISSION_CATEGORIES.ROLE_MANAGEMENT,
  
  [PERMISSIONS.VIEW_PERMISSIONS]: PERMISSION_CATEGORIES.ROLE_MANAGEMENT,
  [PERMISSIONS.CAN_ADD_PERMISSION_TO_ROLE]: PERMISSION_CATEGORIES.ROLE_MANAGEMENT,
  [PERMISSIONS.CAN_REMOVE_PERMISSION_FROM_ROLE]: PERMISSION_CATEGORIES.ROLE_MANAGEMENT,
  
  [PERMISSIONS.VIEW_SYSTEM_SETTINGS]: PERMISSION_CATEGORIES.SYSTEM_CONFIG,
  [PERMISSIONS.MANAGE_SYSTEM_SETTINGS]: PERMISSION_CATEGORIES.SYSTEM_CONFIG,
  [PERMISSIONS.VIEW_FEATURE_FLAGS]: PERMISSION_CATEGORIES.SYSTEM_CONFIG,
  [PERMISSIONS.MANAGE_FEATURE_FLAGS]: PERMISSION_CATEGORIES.SYSTEM_CONFIG,
  
  [PERMISSIONS.VIEW_TRANSACTIONS]: PERMISSION_CATEGORIES.DATA_MANAGEMENT,
  [PERMISSIONS.MANAGE_TRANSACTIONS]: PERMISSION_CATEGORIES.DATA_MANAGEMENT,
  [PERMISSIONS.EXPORT_DATA]: PERMISSION_CATEGORIES.DATA_MANAGEMENT,
  [PERMISSIONS.IMPORT_DATA]: PERMISSION_CATEGORIES.DATA_MANAGEMENT,
  
  [PERMISSIONS.VIEW_NOTIFICATIONS]: PERMISSION_CATEGORIES.NOTIFICATIONS,
  [PERMISSIONS.SEND_NOTIFICATIONS]: PERMISSION_CATEGORIES.NOTIFICATIONS,
  [PERMISSIONS.MANAGE_TEMPLATES]: PERMISSION_CATEGORIES.NOTIFICATIONS,
  [PERMISSIONS.DELETE_NOTIFICATIONS]: PERMISSION_CATEGORIES.NOTIFICATIONS,
  
  [PERMISSIONS.VIEW_LOGS]: PERMISSION_CATEGORIES.AUDIT_LOGS,
  [PERMISSIONS.EXPORT_LOGS]: PERMISSION_CATEGORIES.AUDIT_LOGS,
  [PERMISSIONS.CREATE_LOGS]: PERMISSION_CATEGORIES.AUDIT_LOGS,
  
  [PERMISSIONS.VIEW_API_KEYS]: PERMISSION_CATEGORIES.API_KEYS,
  [PERMISSIONS.CREATE_API_KEY]: PERMISSION_CATEGORIES.API_KEYS,
  [PERMISSIONS.DELETE_API_KEY]: PERMISSION_CATEGORIES.API_KEYS,
  
  [PERMISSIONS.VIEW_ANALYTICS]: PERMISSION_CATEGORIES.ANALYTICS,
  [PERMISSIONS.EXPORT_ANALYTICS]: PERMISSION_CATEGORIES.ANALYTICS,
  
  [PERMISSIONS.VIEW_DASHBOARD]: PERMISSION_CATEGORIES.DASHBOARD,
}

// Role definitions
export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  SUPPORT_STAFF: 'support_staff',
  CONTENT_MANAGER: 'content_manager',
} as const

export type Role = typeof ROLES[keyof typeof ROLES]

// Default role permissions
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.VIEW_ROLES,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.SEND_NOTIFICATIONS,
    PERMISSIONS.VIEW_LOGS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_SYSTEM_SETTINGS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.MANAGE_TRANSACTIONS,
  ],
  [ROLES.SUPPORT_STAFF]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.SEND_NOTIFICATIONS,
    PERMISSIONS.VIEW_LOGS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.CONTENT_MANAGER]: [
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.MANAGE_TRANSACTIONS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
}

/**
 * Check if user has a specific permission
 */
export function hasPermission(userPermissions: string[], permission: Permission): boolean {
  return userPermissions.includes(permission)
}

/**
 * Check if user has any of the specified permissions
 */
export function hasAnyPermission(userPermissions: string[], permissions: Permission[]): boolean {
  return permissions.some(permission => userPermissions.includes(permission))
}

/**
 * Check if user has all of the specified permissions
 */
export function hasAllPermissions(userPermissions: string[], permissions: Permission[]): boolean {
  return permissions.every(permission => userPermissions.includes(permission))
}

/**
 * Get permissions for a role
 */
export function getRolePermissions(role: Role): Permission[] {
  return ROLE_PERMISSIONS[role] || []
}

